name: Deploy to Server on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo $secrets.SERVERS_HOST
          cd /home/ratenet/Ratenet-webserver/
          git pull origin main
          yarn install
          nohup yarn run dev >> app.log 2>&1 &
          # Add any other deployment scripts here, like restarting services
